project:
  type: website
  output-dir: docs

website:
  title: "Melody Wu"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: posts/index.qmd    # ← 新加
        text: Blog               # ← 新加
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false