project:
  type: website
  output-dir: docs        # GitHub Pages 需要这个

website:
  title: "Melody Wu"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false